CREATE TABLE "external_refs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "external_refs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"entity_type" text NOT NULL,
	"entity_id" bigint NOT NULL,
	"provider" text NOT NULL,
	"external_id" text NOT NULL,
	"url" text,
	CONSTRAINT "external_refs_entity_type_check" CHECK ("external_refs"."entity_type" in ('team', 'player', 'tournament', 'series', 'map', 'league')),
	CONSTRAINT "external_refs_provider_check" CHECK ("external_refs"."provider" in ('liquipedia', 'opendota', 'stratz', 'steam', 'pandascore', 'grid'))
);
--> statement-breakpoint
CREATE TABLE "heroes" (
	"id" smallint PRIMARY KEY NOT NULL,
	"code" text NOT NULL,
	"name_ru" text NOT NULL,
	"icon_url" text
);
--> statement-breakpoint
CREATE TABLE "players" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "players_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nickname" text NOT NULL,
	"real_name" text,
	"country_code" char(2),
	"steam_account_id" bigint,
	"photo_url" text,
	"photo_license" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "players_steam_account_id_unique" UNIQUE("steam_account_id")
);
--> statement-breakpoint
CREATE TABLE "team_rosters" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "team_rosters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"team_id" bigint NOT NULL,
	"player_id" bigint NOT NULL,
	"position" smallint,
	"role" text NOT NULL,
	"valid_from" date NOT NULL,
	"valid_to" date,
	CONSTRAINT "team_rosters_position_check" CHECK ("team_rosters"."position" between 1 and 5),
	CONSTRAINT "team_rosters_role_check" CHECK ("team_rosters"."role" in ('player', 'standin', 'coach'))
);
--> statement-breakpoint
CREATE TABLE "teams" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "teams_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"tag" text NOT NULL,
	"country_code" char(2),
	"logo_url" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "map_draft" (
	"map_id" bigint,
	"order_no" smallint,
	"team_id" bigint NOT NULL,
	"hero_id" smallint NOT NULL,
	"is_pick" boolean NOT NULL,
	CONSTRAINT "map_draft_map_id_order_no_pk" PRIMARY KEY("map_id","order_no")
);
--> statement-breakpoint
CREATE TABLE "maps" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "maps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"series_id" bigint NOT NULL,
	"map_no" smallint NOT NULL,
	"dota_match_id" bigint,
	"radiant_team_id" bigint,
	"dire_team_id" bigint,
	"winner_team_id" bigint,
	"duration_s" integer,
	"started_at" timestamp with time zone,
	"ended_at" timestamp with time zone,
	"status" text NOT NULL,
	"data_tier" text NOT NULL,
	"parsed_at" timestamp with time zone,
	CONSTRAINT "maps_dota_match_id_unique" UNIQUE("dota_match_id"),
	CONSTRAINT "maps_map_no_check" CHECK ("maps"."map_no" between 1 and 5),
	CONSTRAINT "maps_status_check" CHECK ("maps"."status" in ('live', 'finished', 'void')),
	CONSTRAINT "maps_data_tier_check" CHECK ("maps"."data_tier" in ('live', 'basic', 'parsed'))
);
--> statement-breakpoint
CREATE TABLE "organizers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organizers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"slug" text,
	CONSTRAINT "organizers_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "player_map_stats" (
	"map_id" bigint,
	"player_id" bigint,
	"team_id" bigint NOT NULL,
	"hero_id" smallint,
	"is_radiant" boolean NOT NULL,
	"won" boolean,
	"kills" smallint NOT NULL,
	"deaths" smallint NOT NULL,
	"assists" smallint NOT NULL,
	"last_hits" smallint NOT NULL,
	"denies" smallint NOT NULL,
	"gpm" smallint,
	"xpm" smallint,
	"net_worth" integer,
	"hero_damage" integer,
	"building_damage" integer,
	"hero_healing" integer,
	"obs_placed" smallint,
	"obs_killed" smallint,
	"stun_s" numeric(6, 1),
	"camps_stacked" smallint,
	"data_tier" text NOT NULL,
	"extra" jsonb,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "player_map_stats_map_id_player_id_pk" PRIMARY KEY("map_id","player_id"),
	CONSTRAINT "player_map_stats_data_tier_check" CHECK ("player_map_stats"."data_tier" in ('live', 'basic', 'parsed'))
);
--> statement-breakpoint
CREATE TABLE "seasons" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "seasons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"starts_on" date NOT NULL,
	"ends_on" date,
	"status" text NOT NULL,
	"config" jsonb NOT NULL,
	CONSTRAINT "seasons_status_check" CHECK ("seasons"."status" in ('planned', 'active', 'finished'))
);
--> statement-breakpoint
CREATE TABLE "series" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "series_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tournament_id" bigint NOT NULL,
	"stage_id" bigint NOT NULL,
	"group_id" bigint,
	"round_label" text NOT NULL,
	"bracket_side" text,
	"round_no" smallint,
	"slot" smallint,
	"best_of" smallint NOT NULL,
	"team_a_id" bigint,
	"team_b_id" bigint,
	"score_a" smallint DEFAULT 0 NOT NULL,
	"score_b" smallint DEFAULT 0 NOT NULL,
	"winner_team_id" bigint,
	"status" text NOT NULL,
	"scheduled_at" timestamp with time zone,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"next_win_series_id" bigint,
	"next_lose_series_id" bigint,
	CONSTRAINT "series_bracket_side_check" CHECK ("series"."bracket_side" in ('group', 'upper', 'lower', 'final')),
	CONSTRAINT "series_best_of_check" CHECK ("series"."best_of" in (1, 2, 3, 5)),
	CONSTRAINT "series_status_check" CHECK ("series"."status" in ('scheduled', 'live', 'finished', 'forfeit', 'cancelled'))
);
--> statement-breakpoint
CREATE TABLE "stage_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stage_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"stage_id" bigint NOT NULL,
	"label" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stages" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tournament_id" bigint NOT NULL,
	"idx" smallint NOT NULL,
	"name" text NOT NULL,
	"format" text NOT NULL,
	"deadline_at" timestamp with time zone,
	"starts_at" timestamp with time zone,
	"ends_at" timestamp with time zone,
	"status" text NOT NULL,
	CONSTRAINT "stages_format_check" CHECK ("stages"."format" in ('gsl', 'swiss', 'round_robin', 'double_elim', 'single_elim')),
	CONSTRAINT "stages_status_check" CHECK ("stages"."status" in ('upcoming', 'open', 'locked', 'settling', 'settled'))
);
--> statement-breakpoint
CREATE TABLE "streams" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "streams_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tournament_id" bigint NOT NULL,
	"series_id" bigint,
	"platform" text NOT NULL,
	"url" text NOT NULL,
	"language" text,
	CONSTRAINT "streams_platform_check" CHECK ("streams"."platform" in ('twitch', 'youtube', 'vk', 'kick'))
);
--> statement-breakpoint
CREATE TABLE "tournament_teams" (
	"tournament_id" bigint,
	"team_id" bigint,
	"seed" smallint,
	"group_id" bigint,
	"status" text NOT NULL,
	"eliminated_after_stage_id" bigint,
	"final_place" smallint,
	CONSTRAINT "tournament_teams_tournament_id_team_id_pk" PRIMARY KEY("tournament_id","team_id"),
	CONSTRAINT "tournament_teams_status_check" CHECK ("tournament_teams"."status" in ('active', 'eliminated'))
);
--> statement-breakpoint
CREATE TABLE "tournaments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tournaments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"season_id" bigint,
	"organizer_id" bigint,
	"slug" text,
	"name" text NOT NULL,
	"tier" smallint NOT NULL,
	"prize_pool_usd" integer,
	"location" text,
	"starts_at" timestamp with time zone,
	"ends_at" timestamp with time zone,
	"status" text NOT NULL,
	"is_league_round" boolean NOT NULL,
	"skin" text,
	"scoring_ruleset_id" bigint NOT NULL,
	"config" jsonb NOT NULL,
	CONSTRAINT "tournaments_slug_unique" UNIQUE("slug"),
	CONSTRAINT "tournaments_status_check" CHECK ("tournaments"."status" in ('announced', 'open', 'live', 'finished', 'cancelled'))
);
--> statement-breakpoint
CREATE TABLE "data_overrides" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "data_overrides_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"entity_type" text NOT NULL,
	"entity_id" text NOT NULL,
	"field" text NOT NULL,
	"value" jsonb NOT NULL,
	"reason" text NOT NULL,
	"created_by" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ingest_runs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ingest_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"job" text NOT NULL,
	"provider" text NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone,
	"status" text NOT NULL,
	"items_seen" integer,
	"items_changed" integer,
	"error" text,
	CONSTRAINT "ingest_runs_status_check" CHECK ("ingest_runs"."status" in ('ok', 'partial', 'failed'))
);
--> statement-breakpoint
CREATE TABLE "player_map_points" (
	"map_id" bigint,
	"tournament_player_id" bigint,
	"ruleset_id" bigint,
	"raw_points" numeric(7, 2) NOT NULL,
	"points" numeric(7, 2) NOT NULL,
	"breakdown" jsonb NOT NULL,
	"data_tier" text NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "player_map_points_map_id_tournament_player_id_ruleset_id_pk" PRIMARY KEY("map_id","tournament_player_id","ruleset_id"),
	CONSTRAINT "player_map_points_data_tier_check" CHECK ("player_map_points"."data_tier" in ('live', 'basic', 'parsed'))
);
--> statement-breakpoint
CREATE TABLE "player_prices" (
	"tournament_player_id" bigint,
	"stage_id" bigint,
	"price" numeric(4, 1) NOT NULL,
	"change" numeric(3, 1) NOT NULL,
	"reason" text,
	CONSTRAINT "player_prices_tournament_player_id_stage_id_pk" PRIMARY KEY("tournament_player_id","stage_id")
);
--> statement-breakpoint
CREATE TABLE "player_stage_points" (
	"tournament_player_id" bigint,
	"stage_id" bigint,
	"points" numeric(7, 2) NOT NULL,
	"maps_played" smallint NOT NULL,
	"ownership_pct" numeric(5, 2),
	CONSTRAINT "player_stage_points_tournament_player_id_stage_id_pk" PRIMARY KEY("tournament_player_id","stage_id")
);
--> statement-breakpoint
CREATE TABLE "scoring_rulesets" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scoring_rulesets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"version" text,
	"rules" jsonb NOT NULL,
	"role_coefs" jsonb NOT NULL,
	"published_at" timestamp with time zone,
	"notes" text,
	CONSTRAINT "scoring_rulesets_version_unique" UNIQUE("version")
);
--> statement-breakpoint
CREATE TABLE "tournament_players" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tournament_players_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tournament_id" bigint NOT NULL,
	"player_id" bigint NOT NULL,
	"team_id" bigint NOT NULL,
	"position" smallint NOT NULL,
	"is_active" boolean NOT NULL,
	"start_rating" numeric(5, 2),
	"start_price" numeric(4, 1) NOT NULL,
	CONSTRAINT "tournament_players_position_check" CHECK ("tournament_players"."position" between 1 and 5)
);
--> statement-breakpoint
CREATE TABLE "auth_identities" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_identities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"provider" text NOT NULL,
	"provider_uid" text NOT NULL,
	"verified_at" timestamp with time zone,
	CONSTRAINT "auth_identities_provider_check" CHECK ("auth_identities"."provider" in ('device', 'telegram', 'email', 'vk'))
);
--> statement-breakpoint
CREATE TABLE "notification_prefs" (
	"user_id" bigint PRIMARY KEY NOT NULL,
	"round_open" boolean NOT NULL,
	"deadline_reminder" boolean NOT NULL,
	"round_result" boolean NOT NULL,
	"replay_parsed" boolean NOT NULL,
	"channels" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_sessions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"token_hash" "bytea",
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"last_seen_at" timestamp with time zone,
	CONSTRAINT "user_sessions_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"nickname" text NOT NULL,
	"avatar_hue" smallint,
	"favorite_team_id" bigint,
	"locale" text NOT NULL,
	"role" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "users_role_check" CHECK ("users"."role" in ('user', 'admin'))
);
--> statement-breakpoint
CREATE TABLE "lineup_lock_slots" (
	"lock_id" bigint,
	"position" smallint,
	"tournament_player_id" bigint NOT NULL,
	"price_at_lock" numeric(4, 1) NOT NULL,
	CONSTRAINT "lineup_lock_slots_lock_id_position_pk" PRIMARY KEY("lock_id","position")
);
--> statement-breakpoint
CREATE TABLE "lineup_locks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lineup_locks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lineup_id" bigint NOT NULL,
	"stage_id" bigint NOT NULL,
	"captain_tp_id" bigint NOT NULL,
	"chip" text NOT NULL,
	"free_used" smallint NOT NULL,
	"paid_transfers" smallint NOT NULL,
	"penalty" numeric(5, 1) NOT NULL,
	"locked_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "lineup_locks_chip_check" CHECK ("lineup_locks"."chip" in ('none', 'triple', 'wildcard'))
);
--> statement-breakpoint
CREATE TABLE "lineup_slots" (
	"lineup_id" bigint,
	"position" smallint,
	"tournament_player_id" bigint NOT NULL,
	"bought_price" numeric(4, 1) NOT NULL,
	CONSTRAINT "lineup_slots_lineup_id_position_pk" PRIMARY KEY("lineup_id","position"),
	CONSTRAINT "lineup_slots_position_check" CHECK ("lineup_slots"."position" between 1 and 5)
);
--> statement-breakpoint
CREATE TABLE "lineup_stage_scores" (
	"lineup_id" bigint,
	"stage_id" bigint,
	"points" numeric(8, 2) NOT NULL,
	"data_tier" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "lineup_stage_scores_lineup_id_stage_id_pk" PRIMARY KEY("lineup_id","stage_id"),
	CONSTRAINT "lineup_stage_scores_data_tier_check" CHECK ("lineup_stage_scores"."data_tier" in ('live', 'basic', 'parsed'))
);
--> statement-breakpoint
CREATE TABLE "lineups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lineups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"tournament_id" bigint NOT NULL,
	"bank" numeric(4, 1) NOT NULL,
	"free_transfers" smallint NOT NULL,
	"captain_position" smallint,
	"chip_pending" text NOT NULL,
	"triple_used_stage_id" bigint,
	"wildcard_used_stage_id" bigint,
	"first_completed_at" timestamp with time zone,
	"total_points" numeric(8, 2) NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "lineups_free_transfers_check" CHECK ("lineups"."free_transfers" between 0 and 2),
	CONSTRAINT "lineups_captain_position_check" CHECK ("lineups"."captain_position" between 1 and 5),
	CONSTRAINT "lineups_chip_pending_check" CHECK ("lineups"."chip_pending" in ('none', 'triple', 'wildcard'))
);
--> statement-breakpoint
CREATE TABLE "tournament_standings" (
	"tournament_id" bigint,
	"lineup_id" bigint,
	"total_points" numeric(8, 2) NOT NULL,
	"rank" integer NOT NULL,
	"prev_rank" integer,
	"tiebreak" jsonb NOT NULL,
	"is_final" boolean NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tournament_standings_tournament_id_lineup_id_pk" PRIMARY KEY("tournament_id","lineup_id")
);
--> statement-breakpoint
CREATE TABLE "transfers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "transfers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lineup_id" bigint NOT NULL,
	"stage_id" bigint NOT NULL,
	"position" smallint NOT NULL,
	"out_tp_id" bigint NOT NULL,
	"in_tp_id" bigint NOT NULL,
	"out_price" numeric(4, 1) NOT NULL,
	"in_price" numeric(4, 1) NOT NULL,
	"kind" text NOT NULL,
	CONSTRAINT "transfers_kind_check" CHECK ("transfers"."kind" in ('free', 'paid', 'eliminated', 'guaranteed', 'wildcard'))
);
--> statement-breakpoint
CREATE TABLE "pickem_answers" (
	"question_id" bigint,
	"user_id" bigint,
	"answer" jsonb NOT NULL,
	"points" smallint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "pickem_answers_question_id_user_id_pk" PRIMARY KEY("question_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "pickem_questions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pickem_questions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tournament_id" bigint NOT NULL,
	"stage_id" bigint NOT NULL,
	"series_id" bigint,
	"kind" text NOT NULL,
	"title" text NOT NULL,
	"options" jsonb NOT NULL,
	"max_points" smallint NOT NULL,
	"closes_at" timestamp with time zone NOT NULL,
	"correct" jsonb,
	"resolved_at" timestamp with time zone,
	CONSTRAINT "pickem_questions_kind_check" CHECK ("pickem_questions"."kind" in ('series', 'two_of', 'one_of'))
);
--> statement-breakpoint
CREATE TABLE "pickem_results" (
	"tournament_id" bigint,
	"user_id" bigint,
	"points" smallint NOT NULL,
	"max_points" smallint NOT NULL,
	"medal" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "pickem_results_tournament_id_user_id_pk" PRIMARY KEY("tournament_id","user_id"),
	CONSTRAINT "pickem_results_medal_check" CHECK ("pickem_results"."medal" in ('bronze', 'silver', 'gold', 'platinum'))
);
--> statement-breakpoint
CREATE TABLE "league_group_members" (
	"group_id" bigint,
	"user_id" bigint,
	"round_id" bigint NOT NULL,
	"lineup_id" bigint NOT NULL,
	"tier_at_start" smallint NOT NULL,
	"place" smallint,
	"zone" text,
	"tier_after" smallint,
	CONSTRAINT "league_group_members_group_id_user_id_pk" PRIMARY KEY("group_id","user_id"),
	CONSTRAINT "league_group_members_zone_check" CHECK ("league_group_members"."zone" in ('up', 'stay', 'down'))
);
--> statement-breakpoint
CREATE TABLE "league_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "league_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"round_id" bigint NOT NULL,
	"tier_id" smallint NOT NULL,
	"group_no" smallint NOT NULL,
	"pooled_key" text,
	"zone_up" smallint NOT NULL,
	"zone_down" smallint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "league_memberships" (
	"season_id" bigint,
	"user_id" bigint,
	"tier_id" smallint,
	"skip_streak" smallint NOT NULL,
	"best_tier_id" smallint,
	"calibrated_at" timestamp with time zone,
	CONSTRAINT "league_memberships_season_id_user_id_pk" PRIMARY KEY("season_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "league_rounds" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "league_rounds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"season_id" bigint NOT NULL,
	"tournament_id" bigint,
	"round_no" smallint NOT NULL,
	"status" text NOT NULL,
	"groups_formed_at" timestamp with time zone,
	"settled_at" timestamp with time zone,
	CONSTRAINT "league_rounds_tournament_id_unique" UNIQUE("tournament_id"),
	CONSTRAINT "league_rounds_status_check" CHECK ("league_rounds"."status" in ('upcoming', 'grouped', 'settled'))
);
--> statement-breakpoint
CREATE TABLE "league_tiers" (
	"id" smallint PRIMARY KEY NOT NULL,
	"code" text,
	"name_ru" text NOT NULL,
	CONSTRAINT "league_tiers_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "season_ladders" (
	"season_id" bigint,
	"tier_id" smallint,
	"is_active" boolean NOT NULL,
	CONSTRAINT "season_ladders_season_id_tier_id_pk" PRIMARY KEY("season_id","tier_id")
);
--> statement-breakpoint
CREATE TABLE "season_titles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "season_titles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"season_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"title" text NOT NULL,
	"tier_id" smallint,
	"awarded_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "season_titles_title_check" CHECK ("season_titles"."title" in ('best_regular', 'champion', 'best_tier'))
);
--> statement-breakpoint
CREATE TABLE "titan_round_points" (
	"round_id" bigint,
	"user_id" bigint,
	"season_id" bigint NOT NULL,
	"place" smallint NOT NULL,
	"f1_points" smallint NOT NULL,
	CONSTRAINT "titan_round_points_round_id_user_id_pk" PRIMARY KEY("round_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "achievements" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "achievements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"code" text,
	"name_ru" text NOT NULL,
	"category" text NOT NULL,
	"tiers" jsonb,
	CONSTRAINT "achievements_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"kind" text NOT NULL,
	"payload" jsonb NOT NULL,
	"channel" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"sent_at" timestamp with time zone,
	"read_at" timestamp with time zone,
	CONSTRAINT "notifications_channel_check" CHECK ("notifications"."channel" in ('telegram', 'email', 'push', 'inapp'))
);
--> statement-breakpoint
CREATE TABLE "trophies" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trophies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"kind" text NOT NULL,
	"tournament_id" bigint,
	"season_id" bigint,
	"label" text NOT NULL,
	"awarded_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "trophies_kind_check" CHECK ("trophies"."kind" in ('promotion', 'group_first', 'best_stage', 'pickem_medal'))
);
--> statement-breakpoint
CREATE TABLE "user_achievements" (
	"user_id" bigint,
	"achievement_id" bigint,
	"tier" smallint NOT NULL,
	"earned_at" timestamp with time zone DEFAULT now() NOT NULL,
	"context" jsonb,
	CONSTRAINT "user_achievements_user_id_achievement_id_pk" PRIMARY KEY("user_id","achievement_id")
);
--> statement-breakpoint
CREATE TABLE "api_clients" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "api_clients_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"name" text NOT NULL,
	"key_hash" "bytea",
	"scopes" text[] NOT NULL,
	"rate_limit_per_min" integer NOT NULL,
	"revoked_at" timestamp with time zone,
	CONSTRAINT "api_clients_key_hash_unique" UNIQUE("key_hash")
);
--> statement-breakpoint
CREATE TABLE "tenants" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tenants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" text,
	"name" text NOT NULL,
	"branding" jsonb,
	"is_default" boolean NOT NULL,
	CONSTRAINT "tenants_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "webhook_deliveries" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "webhook_deliveries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"subscription_id" bigint NOT NULL,
	"event" text NOT NULL,
	"payload" jsonb NOT NULL,
	"status" text NOT NULL,
	"attempts" smallint NOT NULL,
	"next_attempt_at" timestamp with time zone,
	"delivered_at" timestamp with time zone,
	CONSTRAINT "webhook_deliveries_status_check" CHECK ("webhook_deliveries"."status" in ('pending', 'delivered', 'failed'))
);
--> statement-breakpoint
CREATE TABLE "webhook_subscriptions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "webhook_subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"api_client_id" bigint NOT NULL,
	"url" text NOT NULL,
	"events" text[] NOT NULL,
	"secret_hash" "bytea" NOT NULL,
	"is_active" boolean NOT NULL
);
--> statement-breakpoint
ALTER TABLE "team_rosters" ADD CONSTRAINT "team_rosters_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_rosters" ADD CONSTRAINT "team_rosters_player_id_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "map_draft" ADD CONSTRAINT "map_draft_map_id_maps_id_fk" FOREIGN KEY ("map_id") REFERENCES "public"."maps"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "map_draft" ADD CONSTRAINT "map_draft_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "map_draft" ADD CONSTRAINT "map_draft_hero_id_heroes_id_fk" FOREIGN KEY ("hero_id") REFERENCES "public"."heroes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maps" ADD CONSTRAINT "maps_series_id_series_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maps" ADD CONSTRAINT "maps_radiant_team_id_teams_id_fk" FOREIGN KEY ("radiant_team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maps" ADD CONSTRAINT "maps_dire_team_id_teams_id_fk" FOREIGN KEY ("dire_team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maps" ADD CONSTRAINT "maps_winner_team_id_teams_id_fk" FOREIGN KEY ("winner_team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_map_stats" ADD CONSTRAINT "player_map_stats_map_id_maps_id_fk" FOREIGN KEY ("map_id") REFERENCES "public"."maps"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_map_stats" ADD CONSTRAINT "player_map_stats_player_id_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_map_stats" ADD CONSTRAINT "player_map_stats_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_map_stats" ADD CONSTRAINT "player_map_stats_hero_id_heroes_id_fk" FOREIGN KEY ("hero_id") REFERENCES "public"."heroes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "series" ADD CONSTRAINT "series_tournament_id_tournaments_id_fk" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "series" ADD CONSTRAINT "series_stage_id_stages_id_fk" FOREIGN KEY ("stage_id") REFERENCES "public"."stages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "series" ADD CONSTRAINT "series_group_id_stage_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."stage_groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "series" ADD CONSTRAINT "series_team_a_id_teams_id_fk" FOREIGN KEY ("team_a_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "series" ADD CONSTRAINT "series_team_b_id_teams_id_fk" FOREIGN KEY ("team_b_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "series" ADD CONSTRAINT "series_winner_team_id_teams_id_fk" FOREIGN KEY ("winner_team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "series" ADD CONSTRAINT "series_next_win_series_id_series_id_fk" FOREIGN KEY ("next_win_series_id") REFERENCES "public"."series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "series" ADD CONSTRAINT "series_next_lose_series_id_series_id_fk" FOREIGN KEY ("next_lose_series_id") REFERENCES "public"."series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stage_groups" ADD CONSTRAINT "stage_groups_stage_id_stages_id_fk" FOREIGN KEY ("stage_id") REFERENCES "public"."stages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stages" ADD CONSTRAINT "stages_tournament_id_tournaments_id_fk" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "streams" ADD CONSTRAINT "streams_tournament_id_tournaments_id_fk" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "streams" ADD CONSTRAINT "streams_series_id_series_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tournament_teams" ADD CONSTRAINT "tournament_teams_tournament_id_tournaments_id_fk" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tournament_teams" ADD CONSTRAINT "tournament_teams_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tournament_teams" ADD CONSTRAINT "tournament_teams_group_id_stage_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."stage_groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tournament_teams" ADD CONSTRAINT "tournament_teams_eliminated_after_stage_id_stages_id_fk" FOREIGN KEY ("eliminated_after_stage_id") REFERENCES "public"."stages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tournaments" ADD CONSTRAINT "tournaments_season_id_seasons_id_fk" FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tournaments" ADD CONSTRAINT "tournaments_organizer_id_organizers_id_fk" FOREIGN KEY ("organizer_id") REFERENCES "public"."organizers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tournaments" ADD CONSTRAINT "tournaments_scoring_ruleset_id_scoring_rulesets_id_fk" FOREIGN KEY ("scoring_ruleset_id") REFERENCES "public"."scoring_rulesets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "data_overrides" ADD CONSTRAINT "data_overrides_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_map_points" ADD CONSTRAINT "player_map_points_map_id_maps_id_fk" FOREIGN KEY ("map_id") REFERENCES "public"."maps"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_map_points" ADD CONSTRAINT "player_map_points_tournament_player_id_tournament_players_id_fk" FOREIGN KEY ("tournament_player_id") REFERENCES "public"."tournament_players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_map_points" ADD CONSTRAINT "player_map_points_ruleset_id_scoring_rulesets_id_fk" FOREIGN KEY ("ruleset_id") REFERENCES "public"."scoring_rulesets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_prices" ADD CONSTRAINT "player_prices_tournament_player_id_tournament_players_id_fk" FOREIGN KEY ("tournament_player_id") REFERENCES "public"."tournament_players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_prices" ADD CONSTRAINT "player_prices_stage_id_stages_id_fk" FOREIGN KEY ("stage_id") REFERENCES "public"."stages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_stage_points" ADD CONSTRAINT "player_stage_points_tournament_player_id_tournament_players_id_fk" FOREIGN KEY ("tournament_player_id") REFERENCES "public"."tournament_players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_stage_points" ADD CONSTRAINT "player_stage_points_stage_id_stages_id_fk" FOREIGN KEY ("stage_id") REFERENCES "public"."stages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tournament_players" ADD CONSTRAINT "tournament_players_tournament_id_tournaments_id_fk" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tournament_players" ADD CONSTRAINT "tournament_players_player_id_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tournament_players" ADD CONSTRAINT "tournament_players_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_identities" ADD CONSTRAINT "auth_identities_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_prefs" ADD CONSTRAINT "notification_prefs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_favorite_team_id_teams_id_fk" FOREIGN KEY ("favorite_team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineup_lock_slots" ADD CONSTRAINT "lineup_lock_slots_lock_id_lineup_locks_id_fk" FOREIGN KEY ("lock_id") REFERENCES "public"."lineup_locks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineup_lock_slots" ADD CONSTRAINT "lineup_lock_slots_tournament_player_id_tournament_players_id_fk" FOREIGN KEY ("tournament_player_id") REFERENCES "public"."tournament_players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineup_locks" ADD CONSTRAINT "lineup_locks_lineup_id_lineups_id_fk" FOREIGN KEY ("lineup_id") REFERENCES "public"."lineups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineup_locks" ADD CONSTRAINT "lineup_locks_stage_id_stages_id_fk" FOREIGN KEY ("stage_id") REFERENCES "public"."stages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineup_locks" ADD CONSTRAINT "lineup_locks_captain_tp_id_tournament_players_id_fk" FOREIGN KEY ("captain_tp_id") REFERENCES "public"."tournament_players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineup_slots" ADD CONSTRAINT "lineup_slots_lineup_id_lineups_id_fk" FOREIGN KEY ("lineup_id") REFERENCES "public"."lineups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineup_slots" ADD CONSTRAINT "lineup_slots_tournament_player_id_tournament_players_id_fk" FOREIGN KEY ("tournament_player_id") REFERENCES "public"."tournament_players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineup_stage_scores" ADD CONSTRAINT "lineup_stage_scores_lineup_id_lineups_id_fk" FOREIGN KEY ("lineup_id") REFERENCES "public"."lineups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineup_stage_scores" ADD CONSTRAINT "lineup_stage_scores_stage_id_stages_id_fk" FOREIGN KEY ("stage_id") REFERENCES "public"."stages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineups" ADD CONSTRAINT "lineups_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineups" ADD CONSTRAINT "lineups_tournament_id_tournaments_id_fk" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineups" ADD CONSTRAINT "lineups_triple_used_stage_id_stages_id_fk" FOREIGN KEY ("triple_used_stage_id") REFERENCES "public"."stages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineups" ADD CONSTRAINT "lineups_wildcard_used_stage_id_stages_id_fk" FOREIGN KEY ("wildcard_used_stage_id") REFERENCES "public"."stages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tournament_standings" ADD CONSTRAINT "tournament_standings_tournament_id_tournaments_id_fk" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tournament_standings" ADD CONSTRAINT "tournament_standings_lineup_id_lineups_id_fk" FOREIGN KEY ("lineup_id") REFERENCES "public"."lineups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transfers" ADD CONSTRAINT "transfers_lineup_id_lineups_id_fk" FOREIGN KEY ("lineup_id") REFERENCES "public"."lineups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transfers" ADD CONSTRAINT "transfers_stage_id_stages_id_fk" FOREIGN KEY ("stage_id") REFERENCES "public"."stages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transfers" ADD CONSTRAINT "transfers_out_tp_id_tournament_players_id_fk" FOREIGN KEY ("out_tp_id") REFERENCES "public"."tournament_players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transfers" ADD CONSTRAINT "transfers_in_tp_id_tournament_players_id_fk" FOREIGN KEY ("in_tp_id") REFERENCES "public"."tournament_players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pickem_answers" ADD CONSTRAINT "pickem_answers_question_id_pickem_questions_id_fk" FOREIGN KEY ("question_id") REFERENCES "public"."pickem_questions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pickem_answers" ADD CONSTRAINT "pickem_answers_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pickem_questions" ADD CONSTRAINT "pickem_questions_tournament_id_tournaments_id_fk" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pickem_questions" ADD CONSTRAINT "pickem_questions_stage_id_stages_id_fk" FOREIGN KEY ("stage_id") REFERENCES "public"."stages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pickem_questions" ADD CONSTRAINT "pickem_questions_series_id_series_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pickem_results" ADD CONSTRAINT "pickem_results_tournament_id_tournaments_id_fk" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pickem_results" ADD CONSTRAINT "pickem_results_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_group_members" ADD CONSTRAINT "league_group_members_group_id_league_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."league_groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_group_members" ADD CONSTRAINT "league_group_members_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_group_members" ADD CONSTRAINT "league_group_members_round_id_league_rounds_id_fk" FOREIGN KEY ("round_id") REFERENCES "public"."league_rounds"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_group_members" ADD CONSTRAINT "league_group_members_lineup_id_lineups_id_fk" FOREIGN KEY ("lineup_id") REFERENCES "public"."lineups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_group_members" ADD CONSTRAINT "league_group_members_tier_at_start_league_tiers_id_fk" FOREIGN KEY ("tier_at_start") REFERENCES "public"."league_tiers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_group_members" ADD CONSTRAINT "league_group_members_tier_after_league_tiers_id_fk" FOREIGN KEY ("tier_after") REFERENCES "public"."league_tiers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_groups" ADD CONSTRAINT "league_groups_round_id_league_rounds_id_fk" FOREIGN KEY ("round_id") REFERENCES "public"."league_rounds"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_groups" ADD CONSTRAINT "league_groups_tier_id_league_tiers_id_fk" FOREIGN KEY ("tier_id") REFERENCES "public"."league_tiers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_memberships" ADD CONSTRAINT "league_memberships_season_id_seasons_id_fk" FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_memberships" ADD CONSTRAINT "league_memberships_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_memberships" ADD CONSTRAINT "league_memberships_tier_id_league_tiers_id_fk" FOREIGN KEY ("tier_id") REFERENCES "public"."league_tiers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_memberships" ADD CONSTRAINT "league_memberships_best_tier_id_league_tiers_id_fk" FOREIGN KEY ("best_tier_id") REFERENCES "public"."league_tiers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_rounds" ADD CONSTRAINT "league_rounds_season_id_seasons_id_fk" FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_rounds" ADD CONSTRAINT "league_rounds_tournament_id_tournaments_id_fk" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "season_ladders" ADD CONSTRAINT "season_ladders_season_id_seasons_id_fk" FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "season_ladders" ADD CONSTRAINT "season_ladders_tier_id_league_tiers_id_fk" FOREIGN KEY ("tier_id") REFERENCES "public"."league_tiers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "season_titles" ADD CONSTRAINT "season_titles_season_id_seasons_id_fk" FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "season_titles" ADD CONSTRAINT "season_titles_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "season_titles" ADD CONSTRAINT "season_titles_tier_id_league_tiers_id_fk" FOREIGN KEY ("tier_id") REFERENCES "public"."league_tiers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "titan_round_points" ADD CONSTRAINT "titan_round_points_round_id_league_rounds_id_fk" FOREIGN KEY ("round_id") REFERENCES "public"."league_rounds"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "titan_round_points" ADD CONSTRAINT "titan_round_points_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "titan_round_points" ADD CONSTRAINT "titan_round_points_season_id_seasons_id_fk" FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trophies" ADD CONSTRAINT "trophies_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trophies" ADD CONSTRAINT "trophies_tournament_id_tournaments_id_fk" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trophies" ADD CONSTRAINT "trophies_season_id_seasons_id_fk" FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_achievements" ADD CONSTRAINT "user_achievements_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_achievements" ADD CONSTRAINT "user_achievements_achievement_id_achievements_id_fk" FOREIGN KEY ("achievement_id") REFERENCES "public"."achievements"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "api_clients" ADD CONSTRAINT "api_clients_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhook_deliveries" ADD CONSTRAINT "webhook_deliveries_subscription_id_webhook_subscriptions_id_fk" FOREIGN KEY ("subscription_id") REFERENCES "public"."webhook_subscriptions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhook_subscriptions" ADD CONSTRAINT "webhook_subscriptions_api_client_id_api_clients_id_fk" FOREIGN KEY ("api_client_id") REFERENCES "public"."api_clients"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "external_refs_provider_entity_type_external_id_uq" ON "external_refs" USING btree ("provider","entity_type","external_id");--> statement-breakpoint
CREATE INDEX "external_refs_entity_type_entity_id_idx" ON "external_refs" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "team_rosters_player_id_valid_to_idx" ON "team_rosters" USING btree ("player_id","valid_to");--> statement-breakpoint
CREATE UNIQUE INDEX "maps_series_id_map_no_uq" ON "maps" USING btree ("series_id","map_no");--> statement-breakpoint
CREATE INDEX "player_map_stats_player_id_idx" ON "player_map_stats" USING btree ("player_id");--> statement-breakpoint
CREATE INDEX "series_tournament_id_stage_id_idx" ON "series" USING btree ("tournament_id","stage_id");--> statement-breakpoint
CREATE INDEX "series_status_idx" ON "series" USING btree ("status") WHERE "series"."status" = 'live';--> statement-breakpoint
CREATE UNIQUE INDEX "stages_tournament_id_idx_uq" ON "stages" USING btree ("tournament_id","idx");--> statement-breakpoint
CREATE UNIQUE INDEX "tournament_players_tournament_id_player_id_uq" ON "tournament_players" USING btree ("tournament_id","player_id");--> statement-breakpoint
CREATE UNIQUE INDEX "auth_identities_provider_provider_uid_uq" ON "auth_identities" USING btree ("provider","provider_uid");--> statement-breakpoint
CREATE UNIQUE INDEX "users_tenant_id_lower_nickname_uq" ON "users" USING btree ("tenant_id",lower("nickname"));--> statement-breakpoint
CREATE INDEX "lineup_lock_slots_tournament_player_id_idx" ON "lineup_lock_slots" USING btree ("tournament_player_id");--> statement-breakpoint
CREATE UNIQUE INDEX "lineup_locks_lineup_id_stage_id_uq" ON "lineup_locks" USING btree ("lineup_id","stage_id");--> statement-breakpoint
CREATE UNIQUE INDEX "lineups_user_id_tournament_id_uq" ON "lineups" USING btree ("user_id","tournament_id");--> statement-breakpoint
CREATE INDEX "tournament_standings_tournament_id_rank_idx" ON "tournament_standings" USING btree ("tournament_id","rank");--> statement-breakpoint
CREATE UNIQUE INDEX "league_group_members_round_id_user_id_uq" ON "league_group_members" USING btree ("round_id","user_id");--> statement-breakpoint
CREATE INDEX "notifications_user_id_created_at_idx" ON "notifications" USING btree ("user_id","created_at" DESC NULLS LAST);