-- raw_payloads: партиции по месяцам (docs/09). Drizzle не умеет PARTITION BY — ручная миграция.
-- PK партиционированной таблицы обязан включать ключ партиции → (id, fetched_at).
CREATE TABLE "raw_payloads" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY,
	"provider" text NOT NULL,
	"resource" text NOT NULL,
	"external_id" text,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
	"http_status" smallint,
	"payload" jsonb NOT NULL,
	"payload_hash" bytea NOT NULL,
	CONSTRAINT "raw_payloads_id_fetched_at_pk" PRIMARY KEY ("id", "fetched_at")
) PARTITION BY RANGE ("fetched_at");
--> statement-breakpoint
CREATE UNIQUE INDEX "raw_payloads_provider_resource_external_id_payload_hash_fetched_at_uq"
	ON "raw_payloads" ("provider", "resource", "external_id", "payload_hash", "fetched_at");
--> statement-breakpoint
-- Создать партицию месяца (воркер вызывает заранее на следующий месяц); DEFAULT ловит всё остальное.
CREATE OR REPLACE FUNCTION raw_payloads_ensure_partition(month date) RETURNS void LANGUAGE plpgsql AS $$
DECLARE
	m date := date_trunc('month', month)::date;
	name text := 'raw_payloads_' || to_char(m, 'YYYY_MM');
BEGIN
	EXECUTE format('CREATE TABLE IF NOT EXISTS %I PARTITION OF raw_payloads FOR VALUES FROM (%L) TO (%L)',
		name, m, (m + interval '1 month')::date);
END $$;
--> statement-breakpoint
CREATE TABLE "raw_payloads_default" PARTITION OF "raw_payloads" DEFAULT;
--> statement-breakpoint
SELECT raw_payloads_ensure_partition(d::date)
FROM generate_series(date '2026-09-01', date '2027-12-01', interval '1 month') AS d;
