# Единый источник ER-модели Dota Fantasy. Колонка: (имя, тип, ключи, описание)
# ключи: PK, FK>table, UQ, NN (not null), IX ; несколько через пробел
D = []  # домены
def dom(code, name, desc): d={'code':code,'name':name,'desc':desc,'tables':[]}; D.append(d); return d
def T(d, name, desc, cols, extra=None, rows=None):
    d['tables'].append({'name':name,'desc':desc,'cols':cols,'extra':extra or [],'rows':rows})

ts=[('created_at','timestamptz','NN','')]
# ---------------- каталог
c=dom('catalog','Каталог','Команды, игроки, составы во времени, герои и сопоставление с внешними источниками. Живёт дольше любого турнира.')
T(c,'teams','Команда',[('id','bigint','PK',''),('name','text','NN',''),('tag','text','NN','TS, PARI…'),('country_code','char(2)','',''),('logo_url','text','','свой файл, не логотип организатора'),('updated_at','timestamptz','NN','')],rows='~200')
T(c,'players','Игрок про-сцены',[('id','bigint','PK',''),('nickname','text','NN','текущий ник; ники меняются — не ключ'),('real_name','text','',''),('country_code','char(2)','',''),('steam_account_id','bigint','UQ','account_id (Steam32) — главный ключ сопоставления'),('photo_url','text','',''),('photo_license','text','','источник и права на фото'),('updated_at','timestamptz','NN','')],rows='~1 000')
T(c,'team_rosters','Кто за какую команду играл и когда',[('id','bigint','PK',''),('team_id','bigint','FK>teams NN',''),('player_id','bigint','FK>players NN',''),('position','smallint','','1–5'),('role','text','NN','player | standin | coach'),('valid_from','date','NN',''),('valid_to','date','','null — состав актуален')],extra=['INDEX (player_id, valid_to)'],rows='~3 000')
T(c,'heroes','Герои Dota',[('id','smallint','PK','hero_id из игры'),('code','text','NN','npc_dota_hero_…'),('name_ru','text','NN',''),('icon_url','text','','')],rows='~127')
T(c,'external_refs','Сопоставление с внешними источниками',[('id','bigint','PK',''),('entity_type','text','NN','team | player | tournament | series | map | league'),('entity_id','bigint','NN','id в нашей таблице'),('provider','text','NN','liquipedia | opendota | stratz | steam | pandascore | grid'),('external_id','text','NN',''),('url','text','','')],extra=['UNIQUE (provider, entity_type, external_id)','INDEX (entity_type, entity_id)'],rows='десятки тысяч')

# ---------------- турнир
t=dom('tournament','Турнир и формат','Сезон, турнир, стадии, группы, сетка серий как граф, карты, драфт и статистика игроков на карте.')
T(t,'organizers','Организатор',[('id','bigint','PK',''),('name','text','NN','BLAST, PGL, ESL…'),('slug','text','UQ','')])
T(t,'seasons','Сезон (от TI до TI)',[('id','bigint','PK',''),('name','text','NN','2026/27'),('starts_on','date','NN',''),('ends_on','date','',''),('status','text','NN','planned | active | finished'),('config','jsonb','NN','зоны, размер группы, калибровка, F1-очки')])
T(t,'tournaments','Турнир',[('id','bigint','PK',''),('season_id','bigint','FK>seasons',''),('organizer_id','bigint','FK>organizers',''),('slug','text','UQ','blast-slam-9'),('name','text','NN',''),('tier','smallint','NN','1'),('prize_pool_usd','integer','',''),('location','text','',''),('starts_at','timestamptz','',''),('ends_at','timestamptz','',''),('status','text','NN','announced | open | live | finished | cancelled'),('is_league_round','boolean','NN','раунд лиги сезона'),('skin','text','','оформление'),('scoring_ruleset_id','bigint','FK>scoring_rulesets NN','правила очков на турнир'),('config','jsonb','NN','бюджет, лимиты, трансферы, пороги медалей')],rows='~15 в сезон')
T(t,'stages','Стадия (окно → дедлайн → игры)',[('id','bigint','PK',''),('tournament_id','bigint','FK>tournaments NN',''),('idx','smallint','NN','0, 1, 2…'),('name','text','NN',''),('format','text','NN','gsl | swiss | round_robin | double_elim | single_elim'),('deadline_at','timestamptz','','первая карта стадии'),('starts_at','timestamptz','',''),('ends_at','timestamptz','',''),('status','text','NN','upcoming | open | locked | settling | settled')],extra=['UNIQUE (tournament_id, idx)'])
T(t,'stage_groups','Группа внутри стадии',[('id','bigint','PK',''),('stage_id','bigint','FK>stages NN',''),('label','text','NN','A, B…')])
T(t,'tournament_teams','Участник турнира',[('tournament_id','bigint','PK FK>tournaments',''),('team_id','bigint','PK FK>teams',''),('seed','smallint','',''),('group_id','bigint','FK>stage_groups',''),('status','text','NN','active | eliminated'),('eliminated_after_stage_id','bigint','FK>stages',''),('final_place','smallint','','')])
T(t,'series','Серия (узел сетки)',[('id','bigint','PK',''),('tournament_id','bigint','FK>tournaments NN',''),('stage_id','bigint','FK>stages NN',''),('group_id','bigint','FK>stage_groups',''),('round_label','text','NN','«Верхняя сетка · 1/4»'),('bracket_side','text','','group | upper | lower | final'),('round_no','smallint','',''),('slot','smallint','','позиция в раунде'),('best_of','smallint','NN','1 | 2 | 3 | 5'),('team_a_id','bigint','FK>teams','null — ещё не определена'),('team_b_id','bigint','FK>teams',''),('score_a','smallint','NN','0'),('score_b','smallint','NN','0'),('winner_team_id','bigint','FK>teams',''),('status','text','NN','scheduled | live | finished | forfeit | cancelled'),('scheduled_at','timestamptz','',''),('started_at','timestamptz','',''),('finished_at','timestamptz','',''),('next_win_series_id','bigint','FK>series','куда идёт победитель'),('next_lose_series_id','bigint','FK>series','куда идёт проигравший')],extra=['INDEX (tournament_id, stage_id)','INDEX (status) WHERE status = \'live\''],rows='~50 на турнир')
T(t,'streams','Трансляции',[('id','bigint','PK',''),('tournament_id','bigint','FK>tournaments NN',''),('series_id','bigint','FK>series','null — канал турнира'),('platform','text','NN','twitch | youtube | vk | kick'),('url','text','NN',''),('language','text','','ru, en')])
T(t,'maps','Карта (одна игра серии)',[('id','bigint','PK',''),('series_id','bigint','FK>series NN',''),('map_no','smallint','NN','1…5'),('dota_match_id','bigint','UQ','match_id Valve; null до старта'),('radiant_team_id','bigint','FK>teams',''),('dire_team_id','bigint','FK>teams',''),('winner_team_id','bigint','FK>teams',''),('duration_s','integer','',''),('started_at','timestamptz','',''),('ended_at','timestamptz','',''),('status','text','NN','live | finished | void (ремейк)'),('data_tier','text','NN','live | basic | parsed'),('parsed_at','timestamptz','','')],extra=['UNIQUE (series_id, map_no)'],rows='~150 на турнир')
T(t,'map_draft','Пики и баны карты',[('map_id','bigint','PK FK>maps',''),('order_no','smallint','PK',''),('team_id','bigint','FK>teams NN',''),('hero_id','smallint','FK>heroes NN',''),('is_pick','boolean','NN','')])
T(t,'player_map_stats','Статистика игрока на карте (сырая, без очков)',[('map_id','bigint','PK FK>maps',''),('player_id','bigint','PK FK>players',''),('team_id','bigint','FK>teams NN',''),('hero_id','smallint','FK>heroes',''),('is_radiant','boolean','NN',''),('won','boolean','','null пока карта идёт'),('kills','smallint','NN','live'),('deaths','smallint','NN','live'),('assists','smallint','NN','live'),('last_hits','smallint','NN','live'),('denies','smallint','NN','live'),('gpm','smallint','','live'),('xpm','smallint','','live'),('net_worth','integer','','live'),('hero_damage','integer','','конец карты'),('building_damage','integer','','конец карты'),('hero_healing','integer','','конец карты'),('obs_placed','smallint','','после разбора'),('obs_killed','smallint','','после разбора'),('stun_s','numeric(6,1)','','после разбора'),('camps_stacked','smallint','','после разбора'),('data_tier','text','NN','live | basic | parsed'),('extra','jsonb','','всё остальное из источника'),('updated_at','timestamptz','NN','')],extra=['INDEX (player_id)'],rows='~1 500 на турнир')

# ---------------- сбор
g=dom('ingest','Сбор данных','Сырые ответы внешних API, журнал запусков и ручные правки аналитика. Позволяет пересчитать всё без повторных запросов.')
T(g,'raw_payloads','Сырой ответ внешнего API',[('id','bigint','PK',''),('provider','text','NN',''),('resource','text','NN','league_matches | match | live_league_games | bracket…'),('external_id','text','',''),('fetched_at','timestamptz','NN','ключ партиции'),('http_status','smallint','',''),('payload','jsonb','NN',''),('payload_hash','bytea','NN','дубликаты не пишем')],extra=['PARTITION BY RANGE (fetched_at) — по месяцу','UNIQUE (provider, resource, external_id, payload_hash, fetched_at)','live-ответы: не чаще 1 раза в минуту на карту, хранить 30 дней'],rows='самая большая таблица')
T(g,'ingest_runs','Журнал запусков сборщиков',[('id','bigint','PK',''),('job','text','NN',''),('provider','text','NN',''),('started_at','timestamptz','NN',''),('finished_at','timestamptz','',''),('status','text','NN','ok | partial | failed'),('items_seen','integer','',''),('items_changed','integer','',''),('error','text','','')])
T(g,'data_overrides','Ручные правки данных',[('id','bigint','PK',''),('entity_type','text','NN','map | player_map_stats | series | tournament_players…'),('entity_id','text','NN',''),('field','text','NN',''),('value','jsonb','NN',''),('reason','text','NN','стендин, ремейк, ошибка источника'),('created_by','bigint','FK>users NN',''),('created_at','timestamptz','NN','')],extra=['применяются поверх данных источника при каждом пересчёте'])

# ---------------- экономика
f=dom('fantasy','Фэнтези: очки и цены','Версии правил очков, пул игроков турнира с ценами и очки отдельно от статистики.')
T(f,'scoring_rulesets','Версия правил очков',[('id','bigint','PK',''),('version','text','UQ','2026.10-a'),('rules','jsonb','NN','очки за статистики'),('role_coefs','jsonb','NN','множители позиций'),('published_at','timestamptz','',''),('notes','text','','')])
T(f,'tournament_players','Игрок в пуле турнира',[('id','bigint','PK',''),('tournament_id','bigint','FK>tournaments NN',''),('player_id','bigint','FK>players NN',''),('team_id','bigint','FK>teams NN',''),('position','smallint','NN','1–5, на турнир не меняется'),('is_active','boolean','NN','false — стендин заменил / снят'),('start_rating','numeric(5,2)','','внутренний, не показываем'),('start_price','numeric(4,1)','NN','4.5–12.5')],extra=['UNIQUE (tournament_id, player_id)'],rows='~80 на турнир')
T(f,'player_prices','Цена на начало стадии',[('tournament_player_id','bigint','PK FK>tournament_players',''),('stage_id','bigint','PK FK>stages',''),('price','numeric(4,1)','NN',''),('change','numeric(3,1)','NN',''),('reason','text','','очки за карту / вылет (цена заморожена)')])
T(f,'player_map_points','Очки игрока за карту',[('map_id','bigint','PK FK>maps',''),('tournament_player_id','bigint','PK FK>tournament_players',''),('ruleset_id','bigint','PK FK>scoring_rulesets',''),('raw_points','numeric(7,2)','NN',''),('points','numeric(7,2)','NN','× множитель позиции'),('breakdown','jsonb','NN','очки по строкам — для «итога карты»'),('data_tier','text','NN','live | basic | parsed'),('computed_at','timestamptz','NN','')])
T(f,'player_stage_points','Очки игрока за стадию (сумма)',[('tournament_player_id','bigint','PK FK>tournament_players',''),('stage_id','bigint','PK FK>stages',''),('points','numeric(7,2)','NN',''),('maps_played','smallint','NN',''),('ownership_pct','numeric(5,2)','','доля составов с игроком')])

# ---------------- пользователи
u=dom('users','Пользователи','Аккаунт, способы входа, сессии, настройки уведомлений. Привязан к тенанту — задел под B2B.')
T(u,'users','Менеджер',[('id','bigint','PK',''),('tenant_id','bigint','FK>tenants NN','свой сайт = тенант по умолчанию'),('nickname','text','NN',''),('avatar_hue','smallint','',''),('favorite_team_id','bigint','FK>teams',''),('locale','text','NN','ru'),('role','text','NN','user | admin'),('created_at','timestamptz','NN',''),('deleted_at','timestamptz','','мягкое удаление')],extra=['UNIQUE (tenant_id, lower(nickname))'],rows='десятки тысяч')
T(u,'auth_identities','Способ входа',[('id','bigint','PK',''),('user_id','bigint','FK>users NN',''),('provider','text','NN','device | telegram | email | vk'),('provider_uid','text','NN',''),('verified_at','timestamptz','','')],extra=['UNIQUE (provider, provider_uid)'])
T(u,'user_sessions','Сессия',[('id','bigint','PK',''),('user_id','bigint','FK>users NN',''),('token_hash','bytea','UQ',''),('created_at','timestamptz','NN',''),('expires_at','timestamptz','NN',''),('last_seen_at','timestamptz','','')])
T(u,'notification_prefs','Настройки уведомлений',[('user_id','bigint','PK FK>users',''),('round_open','boolean','NN',''),('deadline_reminder','boolean','NN','за 3 часа, если нет состава'),('round_result','boolean','NN',''),('replay_parsed','boolean','NN','«разбор реплея готов»'),('channels','jsonb','NN','telegram, email, push')])

# ---------------- составы
l=dom('lineups','Составы и таблица','Текущий черновик состава, замороженные снимки на каждую стадию, трансферы, очки и таблица турнира.')
T(l,'lineups','Состав менеджера на турнир',[('id','bigint','PK',''),('user_id','bigint','FK>users NN',''),('tournament_id','bigint','FK>tournaments NN',''),('bank','numeric(4,1)','NN',''),('free_transfers','smallint','NN','0–2'),('captain_position','smallint','','1–5'),('chip_pending','text','NN','none | triple | wildcard'),('triple_used_stage_id','bigint','FK>stages',''),('wildcard_used_stage_id','bigint','FK>stages',''),('first_completed_at','timestamptz','','для равенства'),('total_points','numeric(8,2)','NN','денормализовано'),('updated_at','timestamptz','NN','')],extra=['UNIQUE (user_id, tournament_id)'],rows='= активных менеджеров × турниры')
T(l,'lineup_slots','Текущий черновик (то, что видно в окне)',[('lineup_id','bigint','PK FK>lineups',''),('position','smallint','PK','1–5'),('tournament_player_id','bigint','FK>tournament_players NN',''),('bought_price','numeric(4,1)','NN','')])
T(l,'lineup_locks','Снимок состава в дедлайн стадии',[('id','bigint','PK',''),('lineup_id','bigint','FK>lineups NN',''),('stage_id','bigint','FK>stages NN',''),('captain_tp_id','bigint','FK>tournament_players NN',''),('chip','text','NN','none | triple | wildcard'),('free_used','smallint','NN',''),('paid_transfers','smallint','NN',''),('penalty','numeric(5,1)','NN',''),('locked_at','timestamptz','NN','')],extra=['UNIQUE (lineup_id, stage_id)'],rows='× стадии')
T(l,'lineup_lock_slots','Игроки снимка',[('lock_id','bigint','PK FK>lineup_locks',''),('position','smallint','PK',''),('tournament_player_id','bigint','FK>tournament_players NN',''),('price_at_lock','numeric(4,1)','NN','')],extra=['INDEX (tournament_player_id) — кому начислять очки'],rows='самая большая пользовательская')
T(l,'transfers','Трансферы окна (фиксируются в дедлайн)',[('id','bigint','PK',''),('lineup_id','bigint','FK>lineups NN',''),('stage_id','bigint','FK>stages NN','стадия, перед которой окно'),('position','smallint','NN',''),('out_tp_id','bigint','FK>tournament_players NN',''),('in_tp_id','bigint','FK>tournament_players NN',''),('out_price','numeric(4,1)','NN',''),('in_price','numeric(4,1)','NN',''),('kind','text','NN','free | paid | eliminated | guaranteed | wildcard')])
T(l,'lineup_stage_scores','Очки состава за стадию',[('lineup_id','bigint','PK FK>lineups',''),('stage_id','bigint','PK FK>stages',''),('points','numeric(8,2)','NN','с капитаном и штрафом'),('data_tier','text','NN','live | basic | parsed'),('updated_at','timestamptz','NN','')])
T(l,'tournament_standings','Таблица турнира (материализована)',[('tournament_id','bigint','PK FK>tournaments',''),('lineup_id','bigint','PK FK>lineups',''),('total_points','numeric(8,2)','NN',''),('rank','integer','NN',''),('prev_rank','integer','','стрелка ↑↓'),('tiebreak','jsonb','NN','платные трансферы, очки последней стадии, время'),('is_final','boolean','NN','места окончательные после разбора всех карт'),('updated_at','timestamptz','NN','')],extra=['INDEX (tournament_id, rank)'])

# ---------------- мини-лиги
m=dom('social','Мини-лиги','Приватные таблицы по коду.')
T(m,'mini_leagues','Мини-лига',[('id','bigint','PK',''),('code','text','UQ','SLM9-K7QX'),('name','text','NN',''),('owner_user_id','bigint','FK>users NN',''),('scope','text','NN','tournament | season'),('tournament_id','bigint','FK>tournaments',''),('season_id','bigint','FK>seasons',''),('created_at','timestamptz','NN','')])
T(m,'mini_league_members','Участник мини-лиги',[('mini_league_id','bigint','PK FK>mini_leagues',''),('user_id','bigint','PK FK>users',''),('joined_at','timestamptz','NN','')])

# ---------------- прогнозы
p=dom('pickem','Прогнозы','Вопросы по сериям и стадиям, ответы, баллы и медали турнира.')
T(p,'pickem_questions','Вопрос',[('id','bigint','PK',''),('tournament_id','bigint','FK>tournaments NN',''),('stage_id','bigint','FK>stages NN',''),('series_id','bigint','FK>series','для вопросов «кто выиграет серию»'),('kind','text','NN','series | two_of | one_of'),('title','text','NN',''),('options','jsonb','NN','team_id вариантов'),('max_points','smallint','NN',''),('closes_at','timestamptz','NN','дедлайн стадии или старт серии'),('correct','jsonb','','заполняется после итога'),('resolved_at','timestamptz','','')])
T(p,'pickem_answers','Ответ менеджера',[('question_id','bigint','PK FK>pickem_questions',''),('user_id','bigint','PK FK>users',''),('answer','jsonb','NN','{w, sc} | {set} | {w}'),('points','smallint','','после итога'),('updated_at','timestamptz','NN','')])
T(p,'pickem_results','Итог прогнозов за турнир',[('tournament_id','bigint','PK FK>tournaments',''),('user_id','bigint','PK FK>users',''),('points','smallint','NN',''),('max_points','smallint','NN',''),('medal','text','','bronze | silver | gold | platinum'),('updated_at','timestamptz','NN','')])

# ---------------- сезон
s=dom('season','Сезон и лиги','Лестница лиг, членство, раунды, группы по 30 с зонами, Титаны и титулы.')
T(s,'league_tiers','Лиги (справочник)',[('id','smallint','PK','1 Рекрут … 8 Титан'),('code','text','UQ','herald…immortal'),('name_ru','text','NN','')])
T(s,'season_ladders','Какие лиги активны в сезоне',[('season_id','bigint','PK FK>seasons',''),('tier_id','smallint','PK FK>league_tiers',''),('is_active','boolean','NN','фазы 1–3 по аудитории')])
T(s,'league_memberships','Лига менеджера в сезоне',[('season_id','bigint','PK FK>seasons',''),('user_id','bigint','PK FK>users',''),('tier_id','smallint','FK>league_tiers','null — калибровка'),('skip_streak','smallint','NN',''),('best_tier_id','smallint','FK>league_tiers',''),('calibrated_at','timestamptz','','')])
T(s,'league_rounds','Раунд лиги = турнир',[('id','bigint','PK',''),('season_id','bigint','FK>seasons NN',''),('tournament_id','bigint','FK>tournaments UQ',''),('round_no','smallint','NN',''),('status','text','NN','upcoming | grouped | settled'),('groups_formed_at','timestamptz','',''),('settled_at','timestamptz','','')])
T(s,'league_groups','Группа раунда',[('id','bigint','PK',''),('round_id','bigint','FK>league_rounds NN',''),('tier_id','smallint','FK>league_tiers NN',''),('group_no','smallint','NN',''),('pooled_key','text','','сводная таблица нескольких лиг'),('zone_up','smallint','NN','мест в зоне повышения'),('zone_down','smallint','NN','')])
T(s,'league_group_members','Менеджер в группе',[('group_id','bigint','PK FK>league_groups',''),('user_id','bigint','PK FK>users',''),('round_id','bigint','FK>league_rounds NN','для UNIQUE'),('lineup_id','bigint','FK>lineups NN',''),('tier_at_start','smallint','FK>league_tiers NN',''),('place','smallint','',''),('zone','text','','up | stay | down'),('tier_after','smallint','FK>league_tiers','')],extra=['UNIQUE (round_id, user_id)'])
T(s,'titan_round_points','Очки F1 Титанов за раунд',[('round_id','bigint','PK FK>league_rounds',''),('user_id','bigint','PK FK>users',''),('season_id','bigint','FK>seasons NN',''),('place','smallint','NN',''),('f1_points','smallint','NN','25, 18, 15…')])
T(s,'season_titles','Титулы сезона',[('id','bigint','PK',''),('season_id','bigint','FK>seasons NN',''),('user_id','bigint','FK>users NN',''),('title','text','NN','best_regular | champion | best_tier'),('tier_id','smallint','FK>league_tiers',''),('awarded_at','timestamptz','NN','')])

# ---------------- вовлечение
e=dom('engagement','Достижения и уведомления','Достижения с уровнями, трофеи, очередь уведомлений.')
T(e,'achievements','Достижение (справочник)',[('id','bigint','PK',''),('code','text','UQ',''),('name_ru','text','NN',''),('category','text','NN',''),('tiers','jsonb','','пороги уровней')])
T(e,'user_achievements','Полученное достижение',[('user_id','bigint','PK FK>users',''),('achievement_id','bigint','PK FK>achievements',''),('tier','smallint','NN',''),('earned_at','timestamptz','NN',''),('context','jsonb','','турнир, игрок, карта')])
T(e,'trophies','Трофей',[('id','bigint','PK',''),('user_id','bigint','FK>users NN',''),('kind','text','NN','promotion | group_first | best_stage | pickem_medal'),('tournament_id','bigint','FK>tournaments',''),('season_id','bigint','FK>seasons',''),('label','text','NN',''),('awarded_at','timestamptz','NN','')])
T(e,'notifications','Уведомление',[('id','bigint','PK',''),('user_id','bigint','FK>users NN',''),('kind','text','NN',''),('payload','jsonb','NN',''),('channel','text','NN','telegram | email | push | inapp'),('created_at','timestamptz','NN',''),('sent_at','timestamptz','',''),('read_at','timestamptz','','')],extra=['INDEX (user_id, created_at DESC)'])

# ---------------- B2B
b=dom('b2b','B2B и интеграции наружу','Тенанты (фэнтези под чужим брендом), ключи API партнёров, вебхуки.')
T(b,'tenants','Тенант (бренд)',[('id','bigint','PK',''),('slug','text','UQ','default, partner-x'),('name','text','NN',''),('branding','jsonb','','цвета, шрифты, домен'),('is_default','boolean','NN','')])
T(b,'api_clients','Ключ API партнёра',[('id','bigint','PK',''),('tenant_id','bigint','FK>tenants NN',''),('name','text','NN',''),('key_hash','bytea','UQ',''),('scopes','text[]','NN','read:tournaments, read:standings…'),('rate_limit_per_min','integer','NN',''),('revoked_at','timestamptz','','')])
T(b,'webhook_subscriptions','Подписка на события',[('id','bigint','PK',''),('api_client_id','bigint','FK>api_clients NN',''),('url','text','NN',''),('events','text[]','NN','map.scored, stage.locked, stage.settled'),('secret_hash','bytea','NN','подпись запросов'),('is_active','boolean','NN','')])
T(b,'webhook_deliveries','Доставка вебхука',[('id','bigint','PK',''),('subscription_id','bigint','FK>webhook_subscriptions NN',''),('event','text','NN',''),('payload','jsonb','NN',''),('status','text','NN','pending | delivered | failed'),('attempts','smallint','NN',''),('next_attempt_at','timestamptz','',''),('delivered_at','timestamptz','','')])

# связи: (from_table, to_table, card, label) выводим из FK
def rels():
    R=[]
    for d in D:
        for tb in d['tables']:
            for (n,ty,k,_) in tb['cols']:
                for part in k.split():
                    if part.startswith('FK>'):
                        R.append((tb['name'],part[3:],n,'NN' in k.split() or 'PK' in k.split()))
    return R
TBL={tb['name']:(d['code'],tb) for d in D for tb in d['tables']}
